#!/usr/bin/env python2
import sys
from lexer import lex
from parser import parse
from interpreter import interpret


USAGE = """{name} [interpret|dump|vm|compile] file"""


def main():
    flag = sys.argv[1]
    file_name = sys.argv[2]
    try:
        with open(file_name, 'r') as f:
            source = f.read()
    except IOError as e:
        sys.stderr.write(
            "can't open file {}: {}\n".format(
                file_name, e.strerror))
        sys.exit(e.errno)
    tokens = lex(source)
    ast = parse(tokens)

    if flag == 'interpret':
        interpret(ast)
    elif flag == 'dump':
        print(ast)
    elif flag == 'vm':
        raise NotImplementedError
    elif flag == 'compile':
        raise NotImplementedError
    else:
        print USAGE.format(name=sys.argv[0])


if __name__ == '__main__':
    if len(sys.argv) != 3:
        print USAGE.format(name=sys.argv[0])
    else:
        main()
